//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algarve_Destino_Seguro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public long ID { get; set; }
        public string CommunicationTypeName { get; set; }
        public string CommunicationStateName { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string Attachment { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public System.DateTime SentOn { get; set; }
        public System.DateTime ReceivedOn { get; set; }
    
        public virtual CommunicationType CommunicationType { get; set; }
        public virtual CommunicationState CommunicationState { get; set; }
    }
}
