//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algarve_Destino_Seguro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.CountryLanguage = new HashSet<CountryLanguage>();
            this.Entity = new HashSet<Entity>();
        }
    
        public int Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CountryLanguage> CountryLanguage { get; set; }
        public virtual ICollection<Entity> Entity { get; set; }
    }
}
