//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algarve_Destino_Seguro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityLanguage
    {
        public string LanguageCode { get; set; }
        public string EntityName { get; set; }
        public string EntityZipCode { get; set; }
        public string TranslatedName { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
