//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algarve_Destino_Seguro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentifiedZoneSchedule
    {
        public string IdentifiedZoneTypeName { get; set; }
        public string IdentifiedZoneName { get; set; }
        public System.TimeSpan Start { get; set; }
        public System.TimeSpan End { get; set; }
    
        public virtual IdentifiedZoneType IdentifiedZoneType { get; set; }
        public virtual IdentifiedZone IdentifiedZone { get; set; }
    }
}
