//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algarve_Destino_Seguro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.ThemeContent = new HashSet<ThemeContent>();
            this.TopicContent = new HashSet<TopicContent>();
            this.SubTopicContent = new HashSet<SubTopicContent>();
            this.Phrase = new HashSet<Phrase>();
            this.EntityTypeLanguage = new HashSet<EntityTypeLanguage>();
            this.CountryLanguage = new HashSet<CountryLanguage>();
            this.EntityLanguage = new HashSet<EntityLanguage>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ThemeContent> ThemeContent { get; set; }
        public virtual ICollection<TopicContent> TopicContent { get; set; }
        public virtual ICollection<SubTopicContent> SubTopicContent { get; set; }
        public virtual ICollection<Phrase> Phrase { get; set; }
        public virtual ICollection<EntityTypeLanguage> EntityTypeLanguage { get; set; }
        public virtual ICollection<CountryLanguage> CountryLanguage { get; set; }
        public virtual ICollection<EntityLanguage> EntityLanguage { get; set; }
    }
}
