//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algarve_Destino_Seguro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phrase
    {
        public Phrase()
        {
            this.Descendent = new HashSet<Phrase>();
        }
    
        public string Code { get; set; }
        public string LanguageCode { get; set; }
        public string PhraseCode { get; set; }
        public string Content { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Phrase Ascendent { get; set; }
        public virtual ICollection<Phrase> Descendent { get; set; }
    }
}
