//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algarve_Destino_Seguro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Visibility = false;
            this.SubTopic = new HashSet<SubTopic>();
            this.TopicContent = new HashSet<TopicContent>();
        }
    
        public string ThemeTitle { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Visibility { get; set; }
        public string Icon { get; set; }
    
        public virtual Theme Theme { get; set; }
        public virtual ICollection<SubTopic> SubTopic { get; set; }
        public virtual ICollection<TopicContent> TopicContent { get; set; }
    }
}
